### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by east825** [east825/Jargon#2]
Sample comment

**Comment by east825** [comment]
Another comment

**Comment by east825** [comment]
/usr/local/java/bin/java -Didea.launcher.port=7533 -Didea.launcher.bin.path=/home/user/development/repos/IDEA/bin -Dfile.encoding=UTF-8 -classpath /usr/local/java/jre/lib/management-agent.jar:/usr/local/java/jre/lib/jsse.jar:/usr/local/java/jre/lib/deploy.jar:/usr/local/java/jre/lib/rt.jar:/usr/local/java/jre/lib/jce.jar:/usr/local/java/jre/lib/javaws.jar:/usr/local/java/jre/lib/charsets.jar:/usr/local/java/jre/lib/resources.jar:/usr/local/java/jre/lib/plugin.jar:/usr/local/java/jre/lib/ext/dnsns.jar:/usr/local/java/jre/lib/ext/sunjce_provider.jar:/usr/local/java/jre/lib/ext/sunpkcs11.jar:/usr/local/java/jre/lib/ext/localedata.jar:/home/user/development/tmp/TasksPlayground/out/production/TasksPlayground:/home/user/development/repos/IDEA/out/classes/production/java-runtime com.intellij.rt.execution.application.AppMain CrushingApp
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Error
    at CrushingApp$1.run(CrushingApp.java:12)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:672)
    at java.awt.EventQueue.access$400(EventQueue.java:81)
    at java.awt.EventQueue$2.run(EventQueue.java:633)
    at java.awt.EventQueue$2.run(EventQueue.java:631)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:642)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

Process finished with exit code 0
